import type { PersonItem } from '../../../entity/PersonItem';
import type { McpToolDescriptor } from '../mcp.service';
import type {
  AiClientTimeContext,
  AiToolErrorPayload,
  AiToolRegistryEntry,
} from '../ai.types';

export const AI_SYSTEM_PROMPT_BASE =
  'You are Songbird, the Sapling assistant. Songbird is your name, and if the user asks for your name you should say that your name is Songbird. Address the user informally when speaking German and consistently use du, dir, dich, dein, and deine; avoid the formal forms Sie and Ihre. Use the persisted page context from the latest user message when it is relevant and answer concisely. Do not expose internal technical identifiers such as raw record handles, autogenerated primary keys, or generic internal IDs in normal user-facing prose. If a tool returns displayValue fields, use those labels for records and relations. If a tool returns internal identifiers, treat them as internal metadata unless the user explicitly asks for that exact identifier. Prefer natural confirmations such as saying that a record was created, updated, or deleted successfully. You may still mention explicit user-facing business identifiers such as a ticket number or external number when they are clearly intended for end users.';

export const AI_SYSTEM_PROMPT_TOOL_GUIDANCE =
  'Use available tools automatically when current Sapling data is needed. Follow the active agent prompt, playbook, memory, tool descriptions, and runtime policy. Before querying or mutating an unfamiliar Sapling entity, inspect its schema first and only use fields and relation names returned by schema tools. If a tool returns queryExecuted:false with status needs_schema_retry, treat it as a repairable schema mismatch: inspect the schema or suggested fields and retry with valid fields. Do not invent URLs, deep links, record detail links, or absolute Sapling addresses; only mention links or paths when tool results provide exact paths.';

export const AI_SYSTEM_PROMPT_VECTOR_GUIDANCE =
  'Use semantic search only for indexed long-text questions and choose the entityHandle that matches the active agent scope and user question.';

export const AI_SYSTEM_PROMPT_KNOWLEDGE_GUIDANCE =
  'Use knowledge_search when the active agent scope and user question call for a combined knowledge lookup across configured knowledge sources.';

export const AI_ASSISTANT_SPEECH_INSTRUCTIONS =
  'Speak as Songbird in a warm, lovely, clear female voice. Speak naturally in the language of the message and do not read Markdown as syntax.';

export const AI_GEMINI_REPEATED_TOOL_CALL_ABORT_MESSAGE =
  'Ich breche die automatische Werkzeugschleife ab, weil derselbe Tool-Aufruf wiederholt fehlgeschlagen ist. Bitte formuliere die Frage konkreter oder pruefe zuerst das Entity-Schema.';

export const AI_GEMINI_TOOL_CALL_LIMIT_MESSAGE =
  'Ich habe die automatische Werkzeugausfuehrung beendet, weil zu viele aufeinanderfolgende Tool-Aufrufe noetig waren. Bitte formuliere die Anfrage konkreter oder nenne die gewuenschte Entity direkt.';

export function buildToolFailureAssistantMessage(
  toolErrors: AiToolErrorPayload[],
): string {
  const firstError = toolErrors[0];
  const errorLine = firstError?.error
    ? `Das Datenwerkzeug hat wiederholt mit folgendem Fehler geantwortet: ${firstError.error}.`
    : 'Das Datenwerkzeug hat wiederholt ungueltige Aufrufe erhalten.';
  const hintLine = firstError?.hints?.[0]
    ? `Hinweis: ${firstError.hints[0]}`
    : 'Hinweis: Pruefe zuerst das Entity-Schema und verwende nur dort aufgefuehrte Felder und Operatoren.';

  return `${errorLine} ${hintLine}`.trim();
}

export function buildSystemInstruction(options?: {
  includeToolGuidance?: boolean;
  user?: PersonItem;
  clientTimeContext?: AiClientTimeContext;
  referenceDate?: Date;
  agentInstruction?: string | null;
}): string {
  const referenceDate = options?.referenceDate ?? new Date();
  const toolInstruction = options?.includeToolGuidance
    ? ` ${AI_SYSTEM_PROMPT_TOOL_GUIDANCE} ${AI_SYSTEM_PROMPT_VECTOR_GUIDANCE} ${AI_SYSTEM_PROMPT_KNOWLEDGE_GUIDANCE}`
    : '';
  const agentInstruction = options?.agentInstruction?.trim()
    ? ` Agent-specific instructions: ${options.agentInstruction.trim()}`
    : '';

  return `${AI_SYSTEM_PROMPT_BASE}${agentInstruction}${toolInstruction} ${buildCurrentDateInstruction(
    referenceDate,
    options?.user,
    options?.clientTimeContext,
  )}`.trim();
}

export function buildCurrentDateInstruction(
  referenceDate: Date = new Date(),
  user?: PersonItem,
  clientTimeContext?: AiClientTimeContext,
): string {
  const offsetMinutes = -referenceDate.getTimezoneOffset();
  const localeTimeZone = resolveUserTimeZone(user, clientTimeContext);
  const localeName = resolveUserLocale(user, clientTimeContext);
  const clientReferenceDate = clientTimeContext?.currentDate ?? referenceDate;
  const clientReportedLine = clientTimeContext?.currentDate
    ? `Client reported current date and time: ${clientTimeContext.currentDate.toISOString()}.`
    : null;
  const clientOffsetLine = Number.isFinite(clientTimeContext?.utcOffsetMinutes)
    ? `Client reported timezone offset at request time: UTC${formatUtcOffset(clientTimeContext?.utcOffsetMinutes ?? 0)}.`
    : null;

  return [
    `Current UTC date and time: ${referenceDate.toISOString()}.`,
    `Server local date: ${formatLocalDate(referenceDate)}.`,
    `Server timezone offset: UTC${formatUtcOffset(offsetMinutes)}.`,
    clientReportedLine,
    clientOffsetLine,
    `User locale date and time: ${formatZonedDateTime(clientReferenceDate, localeTimeZone, localeName)} (${localeTimeZone}).`,
    `Interpret relative date expressions such as "today", "yesterday", "this week", and "this month" using the ${localeTimeZone} user locale date unless the user explicitly specifies a different date or timezone.`,
    `When the user gives a time without timezone in German or local phrasing, interpret it as ${localeTimeZone} local time and include the correct offset in tool payloads, for example use 20:00 ${localeTimeZone} rather than 20:00 UTC unless UTC is explicitly requested.`,
  ]
    .filter((line): line is string => !!line)
    .join(' ');
}

export function buildToolSummary(availableTools: McpToolDescriptor[]): string {
  if (availableTools.length === 0) {
    return '';
  }

  return `\n\nAvailable MCP tools: ${availableTools
    .map((tool) => `${tool.serverName}.${tool.toolName}`)
    .join(
      ', ',
    )}. Use them automatically when they are needed. Direct execution is also available with messages like /tool server.tool {"key":"value"}.`;
}

export function buildGeminiJsonStringDescription(description: unknown): string {
  const prefix =
    typeof description === 'string' && description.trim()
      ? `${description.trim()} `
      : '';

  return `${prefix}Provide this value as a JSON string.`.trim();
}

export function buildGeminiToolPayloadDescription(
  entry: AiToolRegistryEntry,
): string {
  const schema = normalizeJsonSchema(entry.descriptor.inputSchema);
  const properties =
    schema?.properties && typeof schema.properties === 'object'
      ? Object.keys(schema.properties)
      : [];
  const propertyHint =
    properties.length > 0
      ? `Include a JSON object with keys like: ${properties.join(', ')}.`
      : "Include a JSON object with this tool's arguments.";

  return `${propertyHint} Provide the full object as a JSON string.`;
}

export function normalizeJsonSchema(
  schema?: Record<string, unknown> | null,
): Record<string, unknown> | null {
  if (!schema || typeof schema !== 'object') {
    return null;
  }

  const anyOf = Array.isArray(schema.anyOf) ? schema.anyOf : null;

  if (anyOf) {
    const firstObjectSchema = anyOf.find(
      (item): item is Record<string, unknown> =>
        item != null &&
        typeof item === 'object' &&
        (item as Record<string, unknown>).type === 'object',
    );

    if (firstObjectSchema) {
      return normalizeJsonSchema(firstObjectSchema);
    }
  }

  return schema;
}

function resolveUserLocale(
  user?: PersonItem,
  clientTimeContext?: AiClientTimeContext,
): string {
  if (clientTimeContext?.locale?.trim()) {
    return clientTimeContext.locale.trim();
  }

  const languageHandle =
    user?.language && typeof user.language !== 'string'
      ? user.language.handle
      : undefined;

  return languageHandle === 'de' || !languageHandle ? 'de-DE' : languageHandle;
}

function resolveUserTimeZone(
  user?: PersonItem,
  clientTimeContext?: AiClientTimeContext,
): string {
  if (isValidTimeZone(clientTimeContext?.timeZone)) {
    return clientTimeContext.timeZone?.trim() ?? 'UTC';
  }

  void user;
  const serverTimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  return isValidTimeZone(serverTimeZone) ? serverTimeZone : 'UTC';
}

function formatUtcOffset(offsetMinutes: number): string {
  const sign = offsetMinutes >= 0 ? '+' : '-';
  const absoluteMinutes = Math.abs(Math.trunc(offsetMinutes));
  const hours = Math.floor(absoluteMinutes / 60)
    .toString()
    .padStart(2, '0');
  const minutes = (absoluteMinutes % 60).toString().padStart(2, '0');
  return `${sign}${hours}:${minutes}`;
}

function formatLocalDate(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function formatZonedDateTime(
  date: Date,
  timeZone: string,
  locale: string,
): string {
  const offset = formatTimeZoneOffset(date, timeZone);
  const dateTime = new Intl.DateTimeFormat(locale, {
    timeZone,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  }).format(date);

  return `${dateTime} UTC${offset}`;
}

function formatTimeZoneOffset(date: Date, timeZone: string): string {
  const parts = new Intl.DateTimeFormat('en-US', {
    timeZone,
    timeZoneName: 'longOffset',
  }).formatToParts(date);
  const offset = parts.find((part) => part.type === 'timeZoneName')?.value;
  const match = offset?.match(/GMT([+-]\d{2}:\d{2})/);

  return match?.[1] ?? '+00:00';
}

function isValidTimeZone(value: unknown): value is string {
  if (typeof value !== 'string' || !value.trim()) {
    return false;
  }

  try {
    new Intl.DateTimeFormat('en-US', { timeZone: value.trim() });
    return true;
  } catch {
    return false;
  }
}
