export const SAPLING_MCP_TOOL_DESCRIPTIONS = {
  currentPerson:
    'Return safe profile context for the current authenticated Sapling user, including name, login, company, language, department, and roles. Use this for questions such as "Wer bin ich?", "Welche Rollen habe ich?", or "Zu welcher Firma gehore ich?".',
  entityCatalog:
    'List the registered Sapling entity handles that can be used with the generic CRUD tools. Use this when you are unsure which entity name to query. For questions about where something is located in the app, navigation, or menu, inspect this catalog first to identify likely candidates such as entity, entityGroup, and entityRoute before querying details.',
  entitySchema:
    'Return structured metadata for one Sapling entity, including fields, relation names, referenced entities, required flags, and Sapling options. Use this before building filters, relations, or create/update payloads for an unfamiliar entity. For navigation questions, use this to verify that entity is the page name, entity.group is the group where it appears, entityGroup.parent is an optional parent group, and entityRoute.route is the final route to open.',
  entitySearch:
    'Search the Sapling entity catalog by entity handle, field name, or relation target. Use this when you only know a rough term, a field such as email or assigneePerson, or a partial entity name and need to discover likely entity handles before calling entity_schema or generic tools.',
  genericList:
    'List Sapling generic records with the same read permissions and filters as the current user. Before using complex filters or relations, first inspect the entity with entity_schema and only use fields and relation names returned there. Use MikroORM-style operators such as $eq, $in, $ilike, $and, and $or; common aliases like eq and like are normalized automatically.',
  genericGet:
    'Load one Sapling generic record by handle with the same read permissions as the current user. Use this when you already know the record handle and need the current sanitized record instead of a list.',
  genericTimeline:
    'Load the record-centric timeline for one Sapling record. Use this for history, date span, or recent activity questions about a known record handle.',
  ticketSearch:
    'Search tickets in TicketItem by number, external number, title, problem description, and optionally solution description. Use this for ticket questions, Sage error reports, and known-fix lookups. Prefer searchMode solution when the user explicitly asks for an existing ticket solution or workaround.',
  semanticSearch:
    'Search vectorized Sapling content semantically. Use this for descriptive long-text questions where the wording may differ from stored records. Supported indexed entities include ticket, event, salesOpportunity, effortEstimate, and effortEstimatePosition.',
  genericCreate:
    'Create a Sapling generic record with the same insert permissions as the current user. Inspect required fields and reference fields with entity_schema before creating an unfamiliar entity. Treat autogenerated handles or primary keys in the result as internal metadata and do not expose them in normal user-facing prose unless the user explicitly asks for them.',
  genericUpdate:
    'Update a Sapling generic record with the same update permissions as the current user. Inspect valid fields and relations with entity_schema before updating an unfamiliar entity. Treat autogenerated handles or primary keys in the result as internal metadata and do not expose them in normal user-facing prose unless the user explicitly asks for them.',
  genericDelete:
    'Delete a Sapling generic record with the same delete permissions as the current user.',
} as const;

export const SAPLING_MCP_USAGE_HINTS = {
  currentPerson: [
    'Use this tool when the user asks about their own identity, profile, company, department, language, or roles.',
    'This payload is intentionally sanitized and does not include passwords, session tokens, or refresh tokens.',
  ],
  entitySchema: [
    'Inspect this schema before composing filters or relation names.',
    'Use only field names listed here.',
    'Security-sensitive fields are intentionally omitted from MCP schema responses and mutation payloads.',
    'Do not send auto-increment or generated primary keys in create payloads.',
    'Treat autogenerated handles and raw primary keys as internal metadata unless the user explicitly asks for them.',
    'For app location, navigation, or menu questions, treat entity as the page name, entity.group as the group where it is shown, entityGroup.parent as an optional parent group, and entityRoute.route as the final route to open.',
    'For person/company references, prefer nested filters on relation fields such as assigneePerson.handle or assigneePerson.email.',
    'Use MikroORM operators with a leading $, for example $eq or $ilike.',
  ],
  entitySearch: [
    'Use entity_schema on one of the returned entity handles before composing filters or mutation payloads.',
    'This search matches entity handles, field names, and relation target handles; it does not query record data.',
  ],
  genericGet: [
    'Use this tool when you already know the exact record handle and need the current sanitized record.',
  ],
  ticketSearch: [
    'TicketItem is exposed via the generic entity handle ticket.',
    'Use searchMode solution when the user asks for an existing fix, workaround, or ticket solution.',
  ],
  semanticSearch: [
    'Use semantic search for natural-language questions across vectorized long-text fields such as ticket problems, event descriptions, sales opportunity pain points, requirements, and offer texts.',
    'Use ticket_search for exact ticket numbers, strict keywords, or external references.',
  ],
  toolError: [
    'If you only know a partial handle or field name, start with entity_search.',
    'Inspect the target entity with entity_schema before retrying.',
    'For location, navigation, or menu questions, start with entity_catalog and then inspect entity, entityGroup, and entityRoute.',
    'Use only valid field and relation names from the schema response.',
    'Use MikroORM operators with a leading $, for example $eq, $in, or $ilike.',
  ],
} as const;
