// Seeder for populating the database with initial permission data.
import { EntityManager } from '@mikro-orm/core';
import { Seeder } from '@mikro-orm/seeder';
import { EntityItem } from '../../entity/EntityItem';
import { RoleItem } from '../../entity/RoleItem';
import { PermissionItem } from '../../entity/PermissionItem';

type PermissionMatrix = {
  read: Set<string>;
  insert: Set<string>;
  update: Set<string>;
  delete: Set<string>;
  show: Set<string>;
};

/**
 * @class
 * @version         1.0
 * @author          Martin Rosbund
 * @summary         Seeder for populating the database with initial permission data. Creates missing permissions for all entities and roles.
 */
export class PermissionSeeder extends Seeder {
  private readonly supportPermissions = this.createMatrix({
    read: [
      'company',
      'address',
      'addressType',
      'person',
      'personType',
      'personSession',
      'personDepartment',
      'socialMedia',
      'socialMediaType',
      'workHour',
      'workHourWeek',
      'product',
      'contract',
      'contractService',
      'serverLandscape',
      'serverLandscapeType',
      'serverLandscapeTypeUsage',
      'event',
      'holidayGroup',
      'holiday',
      'eventStatus',
      'eventType',
      'eventDelivery',
      'eventDeliveryStatus',
      'ticket',
      'ticketTimeTracking',
      'ticketPriority',
      'ticketStatus',
      'ticketType',
      'ticketCategory',
      'ticketSource',
      'supportTeam',
      'supportQueue',
      'slaPolicy',
      'emailTemplate',
      'emailDelivery',
      'emailList',
      'teamsTemplate',
      'teamsSubscription',
      'teamsDelivery',
      'teamsDeliveryStatus',
      'companyRelationship',
      'companyRelationshipType',
      'note',
      'noteGroup',
      'phoneCall',
      'document',
      'documentType',
      'information',
      'dashboardTemplate',
      'aiChatSession',
      'aiChatMessage',
    ],
    insert: [
      'company',
      'address',
      'person',
      'personDepartment',
      'socialMedia',
      'workHour',
      'workHourWeek',
      'product',
      'contract',
      'contractService',
      'serverLandscape',
      'event',
      'holidayGroup',
      'holiday',
      'ticket',
      'ticketTimeTracking',
      'supportTeam',
      'supportQueue',
      'slaPolicy',
      'emailTemplate',
      'emailList',
      'teamsTemplate',
      'teamsSubscription',
      'dashboard',
      'dashboardTemplate',
      'companyRelationship',
      'note',
      'phoneCall',
      'information',
      'kpi',
    ],
    update: [
      'company',
      'address',
      'person',
      'personDepartment',
      'socialMedia',
      'workHour',
      'workHourWeek',
      'product',
      'contract',
      'contractService',
      'serverLandscape',
      'event',
      'holidayGroup',
      'holiday',
      'ticket',
      'ticketTimeTracking',
      'supportTeam',
      'supportQueue',
      'slaPolicy',
      'emailTemplate',
      'emailList',
      'teamsTemplate',
      'teamsSubscription',
      'dashboard',
      'dashboardTemplate',
      'companyRelationship',
      'note',
      'phoneCall',
      'document',
      'information',
      'kpi',
    ],
    delete: [
      'socialMedia',
      'workHour',
      'workHourWeek',
      'event',
      'holidayGroup',
      'holiday',
      'ticketTimeTracking',
      'note',
      'phoneCall',
      'document',
      'information',
      'dashboard',
      'kpi',
    ],
    show: [
      'company',
      'address',
      'person',
      'personDepartment',
      'socialMedia',
      'workHour',
      'workHourWeek',
      'product',
      'contract',
      'contractService',
      'serverLandscape',
      'event',
      'holidayGroup',
      'holiday',
      'ticket',
      'ticketTimeTracking',
      'supportTeam',
      'supportQueue',
      'slaPolicy',
      'emailTemplate',
      'emailList',
      'teamsTemplate',
      'teamsSubscription',
      'dashboard',
      'dashboardTemplate',
      'companyRelationship',
      'note',
      'phoneCall',
      'document',
      'information',
      'aiChatSession',
      'aiChatMessage',
    ],
  });

  private readonly salesPermissions = this.createMatrix({
    read: [
      'company',
      'address',
      'addressType',
      'person',
      'personType',
      'personSession',
      'personDepartment',
      'socialMedia',
      'socialMediaType',
      'product',
      'contract',
      'contractService',
      'serverLandscape',
      'serverLandscapeType',
      'serverLandscapeTypeUsage',
      'event',
      'holidayGroup',
      'holiday',
      'eventStatus',
      'eventType',
      'eventDeliveryStatus',
      'ticket',
      'ticketPriority',
      'ticketStatus',
      'ticketType',
      'ticketCategory',
      'ticketSource',
      'emailTemplate',
      'emailDelivery',
      'emailList',
      'teamsTemplate',
      'teamsSubscription',
      'teamsDelivery',
      'teamsDeliveryStatus',
      'companyRelationship',
      'companyRelationshipType',
      'note',
      'noteGroup',
      'phoneCall',
      'salesOpportunity',
      'salesOpportunityStage',
      'salesOpportunityForecast',
      'salesOpportunitySource',
      'document',
      'documentType',
      'information',
      'dashboardTemplate',
      'aiChatSession',
      'aiChatMessage',
    ],
    insert: [
      'company',
      'address',
      'person',
      'personDepartment',
      'socialMedia',
      'product',
      'contract',
      'contractService',
      'event',
      'holidayGroup',
      'holiday',
      'ticket',
      'emailTemplate',
      'emailList',
      'teamsTemplate',
      'teamsSubscription',
      'dashboard',
      'dashboardTemplate',
      'companyRelationship',
      'note',
      'phoneCall',
      'salesOpportunity',
      'information',
      'kpi',
    ],
    update: [
      'company',
      'address',
      'person',
      'personDepartment',
      'socialMedia',
      'product',
      'contract',
      'contractService',
      'event',
      'holidayGroup',
      'holiday',
      'ticket',
      'emailTemplate',
      'emailList',
      'teamsTemplate',
      'teamsSubscription',
      'dashboard',
      'dashboardTemplate',
      'companyRelationship',
      'note',
      'phoneCall',
      'salesOpportunity',
      'document',
      'information',
      'kpi',
    ],
    delete: [
      'socialMedia',
      'event',
      'holidayGroup',
      'holiday',
      'note',
      'phoneCall',
      'salesOpportunity',
      'document',
      'information',
      'dashboard',
      'kpi',
    ],
    show: [
      'company',
      'address',
      'person',
      'personDepartment',
      'socialMedia',
      'product',
      'contract',
      'contractService',
      'serverLandscape',
      'event',
      'holidayGroup',
      'holiday',
      'ticket',
      'emailTemplate',
      'emailList',
      'teamsTemplate',
      'teamsSubscription',
      'dashboardTemplate',
      'companyRelationship',
      'note',
      'phoneCall',
      'salesOpportunity',
      'document',
      'information',
      'aiChatSession',
      'aiChatMessage',
    ],
  });

  private readonly customerPermissions = this.createMatrix({
    read: [
      'company',
      'address',
      'addressType',
      'person',
      'personType',
      'personSession',
      'product',
      'contract',
      'contractService',
      'event',
      'holidayGroup',
      'holiday',
      'eventStatus',
      'eventType',
      'eventDeliveryStatus',
      'ticket',
      'ticketTimeTracking',
      'ticketPriority',
      'ticketStatus',
      'ticketType',
      'ticketCategory',
      'ticketSource',
      'note',
      'phoneCall',
      'document',
      'documentType',
      'information',
      'dashboardTemplate',
      'aiChatSession',
      'aiChatMessage',
    ],
    insert: [
      'ticket',
      'ticketTimeTracking',
      'note',
      'phoneCall',
      'dashboard',
      'dashboardTemplate',
      'kpi',
    ],
    update: [
      'ticket',
      'ticketTimeTracking',
      'note',
      'phoneCall',
      'dashboard',
      'kpi',
    ],
    delete: ['ticketTimeTracking', 'note', 'phoneCall', 'dashboard', 'kpi'],
    show: [
      'company',
      'address',
      'person',
      'product',
      'contract',
      'contractService',
      'event',
      'holiday',
      'ticket',
      'ticketTimeTracking',
      'note',
      'phoneCall',
      'dashboardTemplate',
      'document',
      'information',
      'aiChatSession',
      'aiChatMessage',
    ],
  });

  private readonly contractorPermissions = this.createMatrix({
    read: [
      'company',
      'address',
      'addressType',
      'person',
      'personType',
      'personSession',
      'workHour',
      'workHourWeek',
      'product',
      'contract',
      'contractService',
      'serverLandscape',
      'serverLandscapeType',
      'serverLandscapeTypeUsage',
      'event',
      'holidayGroup',
      'holiday',
      'eventStatus',
      'eventType',
      'eventDeliveryStatus',
      'ticket',
      'ticketTimeTracking',
      'ticketPriority',
      'ticketStatus',
      'ticketType',
      'ticketCategory',
      'ticketSource',
      'supportTeam',
      'supportQueue',
      'note',
      'phoneCall',
      'document',
      'documentType',
      'information',
      'dashboardTemplate',
      'aiChatSession',
      'aiChatMessage',
    ],
    insert: [
      'workHour',
      'workHourWeek',
      'event',
      'holidayGroup',
      'holiday',
      'ticket',
      'ticketTimeTracking',
      'dashboard',
      'dashboardTemplate',
      'note',
      'phoneCall',
      'kpi',
    ],
    update: [
      'workHour',
      'workHourWeek',
      'event',
      'holidayGroup',
      'holiday',
      'ticket',
      'ticketTimeTracking',
      'note',
      'phoneCall',
      'document',
      'information',
      'dashboard',
      'kpi',
    ],
    delete: [
      'workHour',
      'workHourWeek',
      'ticketTimeTracking',
      'note',
      'phoneCall',
      'dashboard',
      'kpi',
    ],
    show: [
      'company',
      'address',
      'person',
      'workHour',
      'workHourWeek',
      'product',
      'contract',
      'contractService',
      'serverLandscape',
      'event',
      'holidayGroup',
      'holiday',
      'ticket',
      'ticketTimeTracking',
      'supportTeam',
      'supportQueue',
      'note',
      'phoneCall',
      'dashboardTemplate',
      'document',
      'information',
      'aiChatSession',
      'aiChatMessage',
    ],
  });

  async run(em: EntityManager): Promise<void> {
    const entities = await em.findAll(EntityItem, { populate: ['group'] });
    const roles = await em.findAll(RoleItem);
    const existingPermissions = await em.findAll(PermissionItem, {
      populate: ['entity', 'role'],
    });

    const existingKeys = new Set(
      existingPermissions.map(
        (permission) =>
          `${permission.entity.handle}|${permission.role.handle ?? ''}`,
      ),
    );

    let hasChanges = false;

    for (const entity of entities) {
      for (const role of roles) {
        const key = `${entity.handle}|${role.handle ?? ''}`;
        const nextPermission = this.getPermissionsForRole(
          entity,
          role.handle ?? 0,
        );
        if (existingKeys.has(key)) {
          continue;
        }

        em.create(PermissionItem, {
          ...nextPermission,
          entity,
          role,
        });
        hasChanges = true;
      }
    }

    if (hasChanges) {
      await em.flush();
    }
  }

  private getPermissionsForRole(entity: EntityItem, roleHandle: number) {
    switch (roleHandle) {
      case 1:
        return {
          allowRead: true,
          allowInsert: entity.canInsert,
          allowUpdate: entity.canUpdate,
          allowDelete: entity.canDelete,
          allowShow: entity.canShow,
        };
      case 2:
        return this.resolveMatrixPermission(entity, this.supportPermissions);
      case 3:
        return this.resolveMatrixPermission(entity, this.salesPermissions);
      case 4:
        return this.resolveMatrixPermission(entity, this.customerPermissions);
      case 5:
        return this.resolveMatrixPermission(entity, this.contractorPermissions);
      default:
        return {
          allowRead: false,
          allowInsert: false,
          allowUpdate: false,
          allowDelete: false,
          allowShow: false,
        };
    }
  }

  private resolveMatrixPermission(
    entity: EntityItem,
    permissions: PermissionMatrix,
  ) {
    return {
      allowRead:
        entity.canRead === false || permissions.read.has(entity.handle),
      allowInsert: entity.canInsert && permissions.insert.has(entity.handle),
      allowUpdate: entity.canUpdate && permissions.update.has(entity.handle),
      allowDelete: entity.canDelete && permissions.delete.has(entity.handle),
      allowShow: entity.canShow && permissions.show.has(entity.handle),
    };
  }

  private createMatrix(matrix: Record<keyof PermissionMatrix, string[]>) {
    return {
      read: new Set(matrix.read),
      insert: new Set(matrix.insert),
      update: new Set(matrix.update),
      delete: new Set(matrix.delete),
      show: new Set(matrix.show),
    };
  }
}
